import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col justify-between bg-zinc-800 text-white">
          <nav className="flex items-center gap-10 justify-center">
            <Link href={"/"}>Home</Link>
            <Link href={"/"}>Login</Link>
          </nav>
          <div className="min-h-screen max-w-screen-xl mx-auto">{children}</div>
          <footer>This an footer ..</footer>
        </main>
      </body>
    </html>
  );
}
