import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";
import AuthProvider from "../config/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" bg-zinc-800 text-white">
          <AuthProvider>
            <Navbar />
            <div className="min-h-screen max-w-screen-xl mx-auto px-5">
              {children}
            </div>
            <Footer />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
